[package]
name = "bevy-rstml"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.13.2"
eyre = "0.6.12"
quote = "1.0.36"
rstml = "0.11.2"
